export const SET_FOLLOWERS = "app/SET_FOLLOWERS";
export const SET_FOLLOWING = "app/SET_FOLLOWING";
export const SET_SEARCH_RESULT = "app/SET_SEARCH_RESULT";
export const REMOVE_SEARCH_RESULT = "app/REMOVE_SEARCH_RESULT";
